import "@/styles/globals.css";
import Head from "next/head";

import { Provider } from "react-redux";
import { wrapper, store } from "../store/store";
function App({ Component, pageProps }) {
  return (
    <Provider store={store}>
      <Head>
        <title>Gestion Ernesto</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/ernestoPerez.png" />
      </Head>
      <Component {...pageProps} />
    </Provider>
  );
}

export default wrapper.withRedux(App);
