import "@/styles/globals.css";
import Head from "next/head";
import {
  ApolloProvider,
  ApolloClient,
  InMemoryCache,
  useMutation,
} from "@apollo/client";
import Cookies from "universal-cookie";
// import { SchemaLink } from "@apollo/client/link/schema";

// import { schema } from "../apollo/schema";

import { Provider, useDispatch } from "react-redux";
import { wrapper, store } from "../store/store";
import { useEffect } from "react";
import { getUerData } from "@/store/actions/authAction";

// function createIsomorphLink() {
//   return new HttpLink({
//     uri: "/api/graphql",
//   });
// }

const client = new ApolloClient({
  uri: "/api/graphql",
  cache: new InMemoryCache(),
});

function App({ Component, pageProps }) {
  const cookies = new Cookies();
  const token = cookies.get("myTokenName");

  const dispatch = useDispatch();

  useEffect(() => {
    if (token) {
      dispatch(getUerData(token));
    }
  }, [token, dispatch]);
  return (
    <ApolloProvider client={client}>
      <Provider store={store}>
        <Head>
          <title>Gestion Ernesto</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/ernestoPerez.png" />
        </Head>
        <Component {...pageProps} />
      </Provider>
    </ApolloProvider>
  );
}

export default wrapper.withRedux(App);
