import "@/styles/globals.css";
import Head from "next/head";
import { ApolloProvider, ApolloClient, InMemoryCache } from "@apollo/client";
// import { SchemaLink } from "@apollo/client/link/schema";

// import { schema } from "../apollo/schema";

import { Provider } from "react-redux";
import { wrapper, store } from "../store/store";

// function createIsomorphLink() {
//   return new HttpLink({
//     uri: "/api/graphql",
//   });
// }

const client = new ApolloClient({
  uri: "/api/graphql",
  cache: new InMemoryCache(),
});

function App({ Component, pageProps }) {
  // const apolloClient = useApollo(pageProps.initialApolloState);
  return (
    <ApolloProvider client={client}>
      <Provider store={store}>
        <Head>
          <title>Gestion Ernesto</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/ernestoPerez.png" />
        </Head>
        <Component {...pageProps} />
      </Provider>
    </ApolloProvider>
  );
}

export default wrapper.withRedux(App);
