import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.scss";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Gestion Ernesto</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/ernestoPerez.png" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <div>
            <Image
              src="/ernestoPerez.png"
              alt="Vercel Logo"
              className={styles.vercelLogo}
              width={200}
              height={200}
              priority
            />
            <Image
              src="/Imagen1.svg"
              alt="Vercel Logo"
              className={styles.vercelLogo}
              width={200}
              height={200}
              priority
            />
          </div>
        </div>
        <div className={styles.label}>
          <h2>
            Esta <span>aplicacion</span> es <span>patrocinada</span> por{" "}
            <span>Ernesto</span> Perez <span>y</span> potenciada{" "}
            <span>por</span> NextJS
          </h2>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}></div>
      </main>
    </>
  );
}
